[package]
org = "ballerina"
name = "mime"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/mime-native-2.0.0-SNAPSHOT.jar"


[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"


[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "1.2.2"

[[platform.java11.dependency]]
path = "./lib/testng-7.4.0.jar"
groupId = "org.testng"
artifactId = "org.testng"
version = "7.4.0"
